// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuszycblrzggdpngtjie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1c3p5Y2JscnpnZ2Rwbmd0amllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzA2ODcsImV4cCI6MjA1ODA0NjY4N30.d1HM_LWCO0UzB6E-meqw_ngI3EEjlWyJ03jvFVBsaB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);